services:
  - type: web
    name: fastapi-service
    env: python
    pythonVersion: 3.10.13
    buildCommand: bash build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: PIP_PREFER_BINARY
        value: "1"
      - key: PIP_ONLY_BINARY
        value: ":all:"
